name: Rest Assured Tests Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Check build environment
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -version

      - name: Execute test suite
        run: mvn clean test
        continue-on-error: true

      - name: Checkout github pages with previous Allure reports
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Generate Allure test report
        uses: andgineer/allure-report@v3.4
        id: allure-report
        if: always()
        with:
          allure-results: target/surefire-reports
          website: gh-pages-dir
          reports-site-path: builds/tests

      - name: Publish Allure test report
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}